
[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
size = 12.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[general]
import = [ "~/.config/alacritty/colors.toml" ]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
