[colors.primary]
background = '#0e1513'
foreground = '#dee4e1'
 
[colors.cursor]
text = '#dee4e1'
cursor = '#bec9c5' 
 
[colors.vi_mode_cursor]
text = '#0e1513'
cursor = '#83d5c4' 
 
[colors.search.matches]
foreground = '#3f4946' 
background = '#abcae4' 
 
[colors.search.focused_match]
foreground = '#3f4946' 
background = '#83d5c4' 
 
[colors.footer_bar]
foreground = '#3f4946' 
background = '#dee4e1' 
 
[colors.hints.start]
foreground = '#3f4946' 
background = '#b1ccc5' 
 
[colors.hints.end]
foreground = '#3f4946' 
background = '#b1ccc5' 
 
[colors.selection]
text = '#0e1513'
background = '#83d5c4'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#83d5c4' 
yellow = '#026b5d' 
blue = '#83d5c4' 
magenta = '#abcae4' 
cyan = '#b1ccc5' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
